"""Additional synthetic closed incidents used to pressure-test SupportAI retrieval."""
from datetime import datetime, timedelta, timezone

from app import db, initialize


ROWS = [
    ("Apex", "Users directory capacity warning", "Runtime alerts show /users11 at 96% capacity and inbound processing is beginning to queue.", "Cause: Retention cleanup did not remove aged working files from /users11.\nImpact: Inbound processing queued and risked stopping.\nActions: Removed approved aged files, verified capacity, and repaired the cleanup schedule.\n\nRelevant log evidence:\n[filesystem] /users11 usage=96% threshold=90%\n[cleanup] purge job exited code 1"),
    ("Apex", "Users filesystem nearly full", "The /users83 application mount is above threshold; scheduled jobs cannot create temporary output.", "Cause: Temporary export files accumulated after a failed cleanup run.\nImpact: Scheduled output could not be written.\nActions: Cleared approved temporary files and reran the cleanup job.\n\nRelevant log evidence:\n[filesystem] /users83 usage=98%\n[job] write failed: no space left on device"),
    ("Volt", "Secure transfer awaiting inbound payload", "The transfer channel reports complete but the application has not consumed partner_443.xml.", "Cause: Consumer polling service was stopped after a maintenance restart.\nImpact: Partner payload remained unprocessed.\nActions: Restarted the consumer, confirmed partner_443.xml was consumed, and monitored the next poll cycle.\n\nRelevant log evidence:\n[cft] transfer status=COMPLETE\n[consumer] polling service state=STOPPED"),
    ("Kinetic", "MQ consumer lag increasing", "Queue depth is rising while the Kinetic consumer group has stopped acknowledging messages.", "Cause: A consumer process exhausted its connection pool and stopped acknowledging.\nImpact: Integration messages accumulated in the queue.\nActions: Restarted the affected consumer, validated acknowledgements, and increased the connection-pool monitoring threshold.\n\nRelevant log evidence:\n[mq] queue_depth=1842\n[mq] consumer acknowledgement age=1260s"),
    ("Vector", "Batch run waiting on database lock", "RECON_BATCH has exceeded its runtime and session waits show a blocking database transaction.", "Cause: A long-running validation transaction held the required table lock.\nImpact: Downstream reconciliation did not start.\nActions: Coordinated approved session termination, reran RECON_BATCH, and added lock-duration monitoring.\n\nRelevant log evidence:\n[database] transaction waiting on blocking session\n[batch] RECON_BATCH state=WAITING"),
    ("Rumble", "Application response time degradation", "Users report slow page responses after a scheduled reporting job began on node 07.", "Cause: The reporting job consumed CPU and caused application thread starvation.\nImpact: Interactive response times breached the service target.\nActions: Moved the job outside peak hours, restarted affected workers, and added runtime alerting.\n\nRelevant log evidence:\n[server] cpu=97%\n[application] worker pool active=80 waiting=74"),
    ("Matrix", "Deployment completed but configuration unchanged", "Release validation shows the service running but the expected endpoint setting is still the prior value.", "Cause: The deployment package omitted the environment-specific configuration artifact.\nImpact: New integration endpoint was not active.\nActions: Deployed the approved configuration artifact, validated checksum, and completed endpoint smoke testing.\n\nRelevant log evidence:\n[deployment] package version=2026.09.1\n[runtime] endpoint value matched previous release"),
    ("Glow", "HTTPS integration certificate rejected", "Outbound calls fail after certificate rotation with a peer validation error.", "Cause: The new certificate chain was missing the intermediate certificate in the application trust store.\nImpact: Outbound HTTPS integration failed.\nActions: Imported the intermediate chain, restarted the connector, and validated a successful handshake.\n\nRelevant log evidence:\n[https] PKIX path building failed\n[connector] remote handshake rejected"),
    # Filesystem capacity: similar symptom, different mount and underlying cause.
    ("Apex", "Application mount threshold breached", "Monitoring reports /users204 at 94% and the nightly archive job has started retrying temporary writes.", "Cause: A failed archive rotation retained compressed files on /users204.\nImpact: Nightly archive output was delayed and the mount risked becoming unavailable.\nActions: Removed approved retained archives, reran rotation, and confirmed the mount returned below threshold.\n\nRelevant log evidence:\n[filesystem] /users204 usage=94% threshold=90%\n[archive] rotation status=FAILED retained_files=418"),
    ("Apex", "Temporary output cannot be written", "The application reports no free space while creating /users56/export_20260926.tmp.", "Cause: A diagnostic dump remained after an earlier process crash.\nImpact: Export generation could not create its temporary file.\nActions: Cleared the approved dump, verified free space, and reran the export.\n\nRelevant log evidence:\n[filesystem] /users56 usage=99%\n[export] open failed: no space left on device"),
    ("Apex", "User filesystem usage rising", "Capacity alert shows /users17 increasing rapidly after a bulk report request.", "Cause: Bulk report output was written to the application filesystem instead of the managed report share.\nImpact: Other scheduled tasks were at risk of write failure.\nActions: Moved the report output to the approved share, removed temporary copies, and corrected the report path.\n\nRelevant log evidence:\n[filesystem] /users17 usage=93%\n[report] output_path=/users17/reports/bulk"),
    # Inbound file and transfer: deliberately varied filenames and symptoms.
    ("Apex", "Inbound payment file missing", "The 06:00 intake did not find payments_20260926.xml in the expected landing directory.", "Cause: The upstream scheduling job failed before publishing the payment file.\nImpact: Payment intake did not begin.\nActions: Confirmed the upstream failure, received the regenerated file, and restarted intake after checksum validation.\n\nRelevant log evidence:\n[intake] dependency missing: payments_20260926.xml\n[source] publish job exit_code=12"),
    ("Volt", "Partner payload received but not processed", "CFT shows orders_778.dat delivered successfully, but it remains in the inbound directory after the poll interval.", "Cause: The consumer service account had an expired credential and could not read the delivered payload.\nImpact: Partner order processing was delayed.\nActions: Renewed the approved service credential, restarted the consumer, and confirmed orders_778.dat was consumed.\n\nRelevant log evidence:\n[cft] transfer status=COMPLETE file=orders_778.dat\n[consumer] authentication failed for polling account"),
    ("Volt", "Secure transfer file remains pending", "The channel completed for catalog_081.csv but the receiving flow has not moved it to processing.", "Cause: A downstream validation process was disabled during a release window.\nImpact: Catalog update was waiting in the landing area.\nActions: Re-enabled the validation process, checked the file format, and monitored successful processing.\n\nRelevant log evidence:\n[cft] file=catalog_081.csv status=COMPLETE\n[validator] service state=DISABLED"),
    ("Apex", "Inbound document arrived late", "invoice_3901.xml was delivered after the scheduled batch had already timed out waiting for it.", "Cause: Upstream delivery exceeded the agreed cutoff after an outbound queue delay.\nImpact: The receiving batch ended without processing the document.\nActions: Validated the late file, reran the receiving batch, and raised monitoring for the upstream cutoff.\n\nRelevant log evidence:\n[batch] wait timeout for invoice_3901.xml\n[transfer] delivery timestamp exceeded cutoff by 37m"),
    # MQ: same platform family, distinct failure modes.
    ("Kinetic", "Queue depth growing after consumer restart", "The event queue is increasing while consumer-k2 reconnects repeatedly and acknowledges no messages.", "Cause: Consumer-k2 used an outdated broker endpoint after a network change.\nImpact: Event processing accumulated in the queue.\nActions: Updated the approved endpoint, restarted consumer-k2, and verified acknowledgement flow.\n\nRelevant log evidence:\n[mq] queue_depth=2317\n[consumer-k2] connection refused broker-old:1414"),
    ("Kinetic", "Message acknowledgements stalled", "The integration queue has unacknowledged messages even though the consumer process is running.", "Cause: A malformed message caused the consumer to stop at the same retrying payload.\nImpact: Later messages were blocked behind the failed payload.\nActions: Isolated the approved failed message, restarted processing, and sent the payload for source correction.\n\nRelevant log evidence:\n[mq] unacknowledged=642\n[consumer] retry limit reached message_id=MSG-88412"),
    ("Kinetic", "MQ channel disconnected", "The application cannot publish status events and the sender channel is inactive.", "Cause: The broker channel certificate had expired.\nImpact: Status events were not delivered to downstream consumers.\nActions: Renewed the approved channel certificate, restarted the sender channel, and validated test publishing.\n\nRelevant log evidence:\n[mq] sender channel status=INACTIVE\n[mq] TLS peer certificate expired"),
    ("Kinetic", "MQ retry queue accumulating", "The retry queue is growing while a transformation worker repeatedly rejects event payload EVT-99207.", "Cause: A source field changed format and the transformation worker could not parse the new payload.\nImpact: Retried events accumulated and delayed downstream status updates.\nActions: Isolated the failed payloads, deployed the approved mapping correction, and replayed the retry queue after validation.\n\nRelevant log evidence:\n[mq] retry_queue_depth=327\n[transform] parse error event=EVT-99207 field=customerReference"),
    # Database and batch: keep the lock evidence specific.
    ("Vector", "Settlement batch blocked by session", "SETTLEMENT_LOAD has waited for more than 45 minutes while the database reports a blocking session.", "Cause: A manual correction transaction retained a lock on the settlement table.\nImpact: Settlement processing did not start and downstream reports were delayed.\nActions: Coordinated approved completion of the blocking transaction, reran SETTLEMENT_LOAD, and added a lock alert.\n\nRelevant log evidence:\n[database] blocked_session=8421 lock=SETTLEMENT_TXN\n[batch] SETTLEMENT_LOAD state=WAITING"),
    ("Vector", "Reconciliation batch failed on database timeout", "RECON_VALIDATE ended after repeated waits against the transaction history table.", "Cause: An unindexed validation query held database resources during peak processing.\nImpact: Reconciliation validation did not complete within the schedule.\nActions: Applied the approved query tuning, reran RECON_VALIDATE, and monitored the next scheduled run.\n\nRelevant log evidence:\n[database] query timeout table=TRANSACTION_HISTORY\n[batch] RECON_VALIDATE exit_code=124"),
    ("Vector", "Batch dependency waiting on database", "The nightly CLOSE_DAY job is queued because its database dependency remains in a locked state.", "Cause: A prior close-day process ended unexpectedly without releasing its application lock.\nImpact: The nightly close sequence could not continue.\nActions: Verified the stale lock with the database team, cleared it through the approved procedure, and restarted CLOSE_DAY.\n\nRelevant log evidence:\n[database] application lock owner=CLOSE_DAY_PREP stale=true\n[batch] CLOSE_DAY dependency=LOCKED"),
    # Deployment/configuration: same outcome, different release mistake.
    ("Matrix", "Release active but feature flag unchanged", "The service reports the new build, but the expected payment-routing flag is still disabled.", "Cause: The production feature-flag value was not included in the release promotion.\nImpact: The new routing behavior was unavailable after deployment.\nActions: Promoted the approved flag value, validated it in runtime configuration, and completed a targeted smoke test.\n\nRelevant log evidence:\n[deployment] build=2026.09.26.2 status=RUNNING\n[config] payment.routing.enabled=false expected=true"),
    ("Matrix", "Service restarted with prior endpoint", "After deployment, outbound calls still target the legacy endpoint despite the package showing the current version.", "Cause: The environment override file was not mounted on the replacement pod.\nImpact: Calls continued to the prior endpoint.\nActions: Mounted the approved override, restarted the pod, and validated the resolved endpoint.\n\nRelevant log evidence:\n[runtime] resolved_endpoint=https://legacy.example\n[deployment] override file not found"),
    ("Matrix", "Deployment validation shows old property", "A post-release check found the retry limit unchanged although the new configuration was approved.", "Cause: The configuration refresh step did not run after deployment.\nImpact: The service continued using the previous retry behavior.\nActions: Performed the approved configuration refresh, validated the live property, and added the check to release validation.\n\nRelevant log evidence:\n[config] retry_limit=3 expected=7\n[deployment] refresh task status=SKIPPED"),
    # TLS: chain, expiry, and hostname are intentionally distinct resolution paths.
    ("Glow", "Outbound TLS handshake failed", "The connector rejects calls to the partner after their certificate change with a hostname verification error.", "Cause: The partner certificate common name did not match the configured endpoint hostname.\nImpact: Outbound partner calls failed before request delivery.\nActions: Confirmed the approved partner hostname, updated the endpoint configuration, and validated the TLS handshake.\n\nRelevant log evidence:\n[tls] hostname verification failed expected=api.partner.example\n[connector] handshake aborted"),
    ("Glow", "Connector trust validation error", "The service fails when connecting to the vendor API and reports an untrusted certificate issuer.", "Cause: The vendor root certificate was absent from the connector trust store.\nImpact: Vendor API integration was unavailable.\nActions: Imported the approved root certificate, restarted the connector, and validated an API health call.\n\nRelevant log evidence:\n[https] unable to find valid certification path\n[truststore] issuer not found"),
    ("Glow", "HTTPS connector certificate expired", "Scheduled API polling stopped because the client certificate expiry threshold was reached.", "Cause: The connector client certificate expired without a completed renewal.\nImpact: Scheduled polling and downstream updates stopped.\nActions: Installed the renewed approved client certificate, restarted polling, and verified a successful authenticated request.\n\nRelevant log evidence:\n[tls] client certificate expired date=2026-09-25\n[poller] authentication handshake failed"),
]


def main():
    initialize()
    now = datetime.now(timezone.utc)
    with db() as conn:
        added = 0
        for offset, (application, title, initial, closing) in enumerate(ROWS):
            app = conn.execute("SELECT * FROM applications WHERE name = ?", (application,)).fetchone()
            if conn.execute("SELECT 1 FROM incidents WHERE title = ? AND initial_description = ?", (title, initial)).fetchone():
                continue
            created = now - timedelta(days=12 - offset)
            cursor = conn.execute("""INSERT INTO incidents(title, title_normalized, application_id, current_team_id, priority, initial_description, status, created_at, acknowledged_at, closed_at, closing_comments)
                VALUES(?,?,?,?,?,?, 'Closed', ?, ?, ?, ?)""", (title, title.casefold(), app["id"], app["primary_team_id"], "High", initial, created.isoformat(), (created + timedelta(minutes=4)).isoformat(), (created + timedelta(minutes=51)).isoformat(), closing))
            incident_id = cursor.lastrowid
            conn.execute("INSERT INTO incident_comments(incident_id, team_id, action, body, created_at) VALUES(?,NULL,'Created',?,?)", (incident_id, initial, created.isoformat()))
            conn.execute("INSERT INTO incident_comments(incident_id, team_id, action, body, created_at) VALUES(?,?, 'Closed', ?, ?)", (incident_id, app["primary_team_id"], closing, (created + timedelta(minutes=51)).isoformat()))
            added += 1
        print(f"Added {added} RAG pressure-test incidents.")


if __name__ == "__main__":
    main()
