"""Create varied, synthetic historical incidents for local RAG evaluation.

The scenarios are anonymized variations of the user's documented production-support
experience. They are deliberately not copies of client tickets or official records.
"""

from datetime import datetime, timedelta, timezone

from app import APPLICATIONS, db, initialize


SCENARIOS = [
    {
        "titles": ["Application availability alert", "Service reported down", "Application health check failed"],
        "initials": [
            "Monitor reported NODE-{node} unavailable immediately after the nightly restart. Application checks completed successfully.",
            "Health check raised a false down alert for service-{node}; process startup completed but the URL check failed briefly.",
            "Application restart completed, then monitoring reported the service unavailable before it was fully ready.",
        ],
        "closures": [
            "Cause: Monitoring resumed before the application was fully available after restart.\nImpact: Repeated false availability incidents.\nActions: Increased the post-start delay and validated the monitoring timing.",
            "Cause: Startup and URL-monitoring checks had a timing race condition.\nImpact: False down alert during the nightly restart.\nActions: Adjusted the startup script wait time and documented the expected restart behavior.",
        ],
    },
    {
        "titles": ["MQ message integration failed", "Messages stuck in queue", "Partner message backlog"],
        "initials": [
            "MQ queue backlog is increasing. Messages for order-{node} remain in pending state and are not integrating.",
            "Integration queue contains stuck messages for batch-{node}. Application processing has stopped for the affected flow.",
            "Multiple messages from the partner flow are not being consumed. Queue depth continues to increase.",
        ],
        "closures": [
            "Cause: Upstream partner sent invalid messages to the queue.\nImpact: Message integration was delayed for two downstream applications.\nActions: Confirmed the common upstream source, cleared the stuck messages with the MQ team, and restarted the flow.",
            "Cause: Malformed partner message prevented queue consumption.\nImpact: Backlog delayed downstream processing.\nActions: Coordinated with the partner and MQ teams, removed invalid messages after approval, and validated reintegration.",
        ],
    },
    {
        "titles": ["Inbound file delivery failed", "CFT file not received", "File delivery missing"],
        "initials": [
            "Expected inbound file {file_name} was not found in the receiving directory when the scheduled job started.",
            "CFT transfer for {file_name} did not complete before the integration window. The batch is waiting for input.",
            "File {file_name} is missing from the expected path. The inbound processing job ended with a generic failure.",
        ],
        "closures": [
            "Cause: Upstream file generation completed after the receiving batch window.\nImpact: Inbound processing was delayed.\nActions: Confirmed the upstream delay, received the file, reran the approved batch, and reviewed the schedule dependency.",
            "Cause: File was not generated by the upstream process.\nImpact: Scheduled integration could not begin.\nActions: Coordinated with the source application team, obtained the file, and restarted the receiving flow after validation.",
        ],
    },
    {
        "titles": ["File processing failed", "Inbound file integration error", "Batch file rejected"],
        "initials": [
            "File {file_name} arrived but was rejected during processing. The application log only shows 'Job failed'.",
            "Inbound file {file_name} is present but has not integrated. Processing log reports an invalid-data condition.",
            "Scheduled file treatment failed for {file_name}; the primary application log contains only a generic batch error.",
        ],
        "closures": [
            "Cause: Invalid value generated by an upstream user action caused the file to fail validation.\nImpact: Business-critical file integration was stopped.\nActions: Documented the failing field, involved the functional owner, and confirmed the file must be corrected upstream before processing.",
            "Cause: File content did not meet the expected format.\nImpact: Integration rejected the inbound record.\nActions: Traced the error through script and processing logs, confirmed the upstream data issue, and processed the corrected replacement file.",
        ],
    },
    {
        "titles": ["Batch job failed", "Scheduled job aborted", "Nightly batch processing error"],
        "initials": [
            "Job {job_name} aborted during the nightly run. Initial log message is 'Job failed' with no detailed application error.",
            "Scheduled batch {job_name} did not complete. Dependent jobs are waiting and the processing window is at risk.",
            "Batch {job_name} ended unexpectedly during the run. Initial checks show application availability is normal.",
        ],
        "closures": [
            "Cause: Job timing conflicted with a dependent process.\nImpact: Downstream batch sequence was delayed.\nActions: Confirmed the dependency, changed the approved execution timing, and monitored the next scheduled run.",
            "Cause: Database lock blocked the batch transaction.\nImpact: The job aborted and delayed dependent processing.\nActions: Identified the locking session with the database team, cleared it safely, and updated the schedule to reduce recurrence.",
            "Cause: Required dependency file arrived after the batch started.\nImpact: Batch could not process its input.\nActions: Validated the delivery timestamps, ran the approved recovery process, and aligned the dependency timing.",
        ],
    },
    {
        "titles": ["Database error caused application outage", "Application stopped after database error", "P1 database availability issue"],
        "initials": [
            "Critical application is unavailable. Primary analysis shows database error ORA-600 and the application process has stopped.",
            "P1 incident: application stopped responding. Database team reports a known Oracle-level error during investigation.",
            "Business-critical service is down. Application log points to a database failure and restart is required for recovery.",
        ],
        "closures": [
            "Cause: Known Oracle ORA-600 issue on the current database version.\nImpact: Business-critical application was unavailable.\nActions: Restarted the application after DBA and stakeholder confirmation, then planned and completed pre-production testing for the database migration.",
            "Cause: Database-level Oracle defect caused the application to stop.\nImpact: P1 outage until service recovery.\nActions: Restored service with the approved restart, documented the long-term version risk, and initiated the migration path.",
        ],
    },
    {
        "titles": ["Deployed change not visible", "Application version change not reflected", "Deployment completed but behavior unchanged"],
        "initials": [
            "New build was deployed to pre-production but the expected change is not visible. Deployment logs show completion.",
            "Application was redeployed but behavior is unchanged. Development team believes the deployment did not apply correctly.",
            "Version deployment completed successfully, yet the tested functionality still matches the previous build.",
        ],
        "closures": [
            "Cause: Deployment package contained files from the previous version.\nImpact: Expected changes were not available for testing.\nActions: Compared package contents with the expected build, rebuilt the package with corrected files, and redeployed successfully.",
            "Cause: Incorrect artifact was supplied in the deployment package.\nImpact: Repeated deployment installed unchanged code.\nActions: Verified logs and runtime files, demonstrated the package mismatch, received the correct build, and completed deployment validation.",
        ],
    },
    {
        "titles": ["Release validation incomplete", "Post-deployment integration missing", "Change task missed dependency"],
        "initials": [
            "Version change is deployed, but a required integration step is incomplete. A dependent file has not been received.",
            "Post-change validation identified a missing file integration. The deployment itself completed without error.",
            "Routine change finished but stakeholder asked for validation of an integration action not yet completed.",
        ],
        "closures": [
            "Cause: Required file-integration action was missed in the change task list.\nImpact: Change could not be considered fully complete.\nActions: Obtained stakeholder permission through L1, ran the required batch, validated file integration, and closed the change the same day.",
            "Cause: Deployment preparation overlooked a dependency listed in the approved change tasks.\nImpact: Related file flow was incomplete after deployment.\nActions: Reviewed the task list, coordinated the dependent application batch, and completed validation before closing.",
        ],
    },
    {
        "titles": ["Application handover validation failed", "Migration handoff checklist rejected", "Post-migration validation issue"],
        "initials": [
            "Application handoff validation returned two failed checklist items after migration. Handover approval is blocked.",
            "Migration review was rejected because server cleanup and required documentation checks are incomplete.",
            "L3 to L2 handover checklist contains unresolved items after the migration validation review.",
        ],
        "closures": [
            "Cause: Backup files remained on the server and required documentation was missing from the handoff package.\nImpact: Application handover approval was rejected.\nActions: Removed obsolete backup files, uploaded the required documentation, completed a second review, and added a peer check before future submissions.",
            "Cause: Routine validation was submitted without a second review.\nImpact: Migration handoff could not proceed.\nActions: Corrected the failed checklist items, passed the new review, and introduced a peer validation step.",
        ],
    },
    {
        "titles": ["Print job stuck", "Printer incident recurring", "Print queue not processing"],
        "initials": [
            "Print job remains stuck and users report the same issue repeatedly. Any action requires client-side confirmation.",
            "Recurring print queue incident received. Job is waiting and support team cannot abort without stakeholder approval.",
            "Printer process is blocked; the client team closes similar tickets as resolved without an explanation.",
        ],
        "closures": [
            "Cause: Client-side team was already clearing the stuck print jobs directly.\nImpact: Support team received unnecessary recurring tickets and added delay.\nActions: Reviewed the process with stakeholders, confirmed application support added no control, and changed routing so future printer incidents go directly to the client team.",
            "Cause: Existing routing sent incidents through an unnecessary support step.\nImpact: Repeated printer tickets created avoidable handoffs.\nActions: Obtained written stakeholder agreement and routed the incident type to the team that resolves it.",
        ],
    },
    {
        "titles": ["Server performance degradation", "Application response time high", "Batch processing slow"],
        "initials": [
            "Application response time is high and batch {job_name} is exceeding its normal runtime. Server health requires investigation.",
            "Business users report slow processing. Child jobs are delayed because server capacity is under pressure.",
            "Nightly process is running longer than the allowed window; CPU and application response time need review.",
        ],
        "closures": [
            "Cause: Server resource pressure affected batch execution time.\nImpact: Child jobs and business processing were delayed.\nActions: Coordinated with infrastructure, increased approved capacity, and monitored the next batch windows for stability.",
            "Cause: Application workload exceeded available server resources during the batch window.\nImpact: Slower response and delayed dependent jobs.\nActions: Reviewed load patterns with infrastructure and application teams, applied the approved capacity change, and validated normal completion.",
        ],
    },
    {
        "titles": ["Secure file transfer stuck", "SFTP file not integrated", "CFT processing backlog"],
        "initials": [
            "File {file_name} completed transfer but remains in the integration directory. CFT/SFTP status is complete and application processing has not started.",
            "Secure transfer succeeded for {file_name}, but the file is stuck before application integration.",
            "CFT file movement is complete; receiving application has not consumed the file and the related batch is pending.",
        ],
        "closures": [
            "Cause: Integration path did not trigger after transfer completion.\nImpact: File remained pending and downstream processing was delayed.\nActions: Checked the transfer and script logs, corrected the approved integration flow, and validated file consumption.",
            "Cause: A dependent processing step had not completed when the file arrived.\nImpact: Secure transfer succeeded but application integration was blocked.\nActions: Validated dependencies and timestamps, completed the approved recovery action, and confirmed end-to-end file processing.",
        ],
    },
    {
        "titles": ["Application disk space alert", "Processing stopped due to disk capacity", "File system threshold breached"],
        "initials": [
            "Application file system reached the configured threshold. New file {file_name} cannot be processed until capacity is restored.",
            "Disk-capacity alert is active and batch output is accumulating faster than cleanup. Processing may stop.",
            "File system usage is high for the application runtime path; scheduled processing is at risk.",
        ],
        "closures": [
            "Cause: Old processing files were not cleared within the expected retention window.\nImpact: Disk capacity alert put scheduled processing at risk.\nActions: Cleared approved obsolete files, verified available capacity, and corrected the cleanup schedule.",
            "Cause: Batch output accumulated without the expected purge activity.\nImpact: File system threshold was breached.\nActions: Restored capacity using the approved cleanup procedure and added monitoring for early warning.",
        ],
    },
]

FILES = ["abcd.xml", "dadv.xml", "orders_0715.dat", "users_204.csv", "claims_811.xml", "sync_112.txt"]
JOBS = ["LOAD_DAILY", "SYNC_NIGHTLY", "RECON_BATCH", "EXPORT_LEDGER", "PROCESS_INBOUND"]
LOG_EVIDENCE = [
    ["[monitor] URL check resumed 5 seconds after restart", "[monitor] service state=DOWN before readiness check completed"],
    ["[mq] pending message count increased; consumer acknowledgement missing", "[mq] message rejected by integration consumer after partner payload validation"],
    ["[transfer] expected file not present at scheduled start time", "[batch] input dependency missing: waiting for upstream delivery"],
    ["[processor] validation rejected inbound record at field level", "[script] file present; application processing returned generic job failure"],
    ["[scheduler] dependent job did not complete before batch start", "[database] transaction waiting on a locking session"],
    ["[database] ORA-600 reported during application failure", "[application] service process stopped after database exception"],
    ["[deployment] package checksum matched previous build", "[runtime] deployed files did not contain expected version change"],
    ["[change] required integration task remained pending after deployment", "[batch] dependent file was not received during post-change validation"],
    ["[validation] handoff checklist item failed: cleanup incomplete", "[validation] required documentation was absent from the package"],
    ["[print] queue state=STUCK; action requires stakeholder confirmation", "[history] similar incidents closed by the client team without support action"],
    ["[server] batch runtime exceeded normal window", "[application] child jobs delayed while resource pressure remained high"],
    ["[transfer] CFT/SFTP status=COMPLETE", "[integration] file remained pending before application consumption"],
    ["[filesystem] runtime path exceeded configured capacity threshold", "[cleanup] expected purge activity did not complete before batch output accumulated"],
]


def add_comment(conn, incident_id, team_id, action, body, timestamp):
    conn.execute(
        "INSERT INTO incident_comments(incident_id, team_id, action, body, created_at) VALUES(?,?,?,?,?)",
        (incident_id, team_id, action, body, timestamp.isoformat()),
    )


def main():
    initialize()
    with db() as conn:
        teams = [dict(row) for row in conn.execute("SELECT id, name FROM teams WHERE name != 'ADMIN' ORDER BY id")]
        applications = [dict(row) for row in conn.execute("SELECT id, name, primary_team_id FROM applications ORDER BY id")]
        added = 0
        start = datetime(2026, 1, 5, 8, 0, tzinfo=timezone.utc)

        for scenario_index, scenario in enumerate(SCENARIOS):
            for variation in range(6):
                application = applications[(scenario_index * 4 + variation) % len(applications)]
                primary_team_id = application["primary_team_id"]
                title = scenario["titles"][variation % len(scenario["titles"])]
                initial = scenario["initials"][variation % len(scenario["initials"])].format(
                    file_name=FILES[(scenario_index + variation) % len(FILES)],
                    job_name=JOBS[(scenario_index * 2 + variation) % len(JOBS)],
                    node=f"{variation + 2:02d}",
                )
                exists = conn.execute(
                    "SELECT id FROM incidents WHERE title = ? AND initial_description = ?", (title, initial)
                ).fetchone()
                if exists:
                    continue

                created = start + timedelta(days=scenario_index * 2 + variation, minutes=variation * 11)
                priority = ["Medium", "High", "Low", "Critical"][(scenario_index + variation) % 4]
                closing_comment = scenario["closures"][variation % len(scenario["closures"])]
                closing_comment += "\n\nRelevant log evidence:\n" + "\n".join(
                    LOG_EVIDENCE[scenario_index][variation % len(LOG_EVIDENCE[scenario_index]) :]
                    or LOG_EVIDENCE[scenario_index]
                )
                cursor = conn.execute(
                    """INSERT INTO incidents(title, title_normalized, application_id, current_team_id, priority,
                         initial_description, status, created_at, acknowledged_at, closed_at, closing_comments)
                       VALUES(?,?,?,?,?,?, 'Closed', ?, ?, ?, ?)""",
                    (
                        title,
                        title.casefold(),
                        application["id"],
                        primary_team_id,
                        priority,
                        initial,
                        created.isoformat(),
                        (created + timedelta(minutes=5)).isoformat(),
                        (created + timedelta(minutes=63)).isoformat(),
                        closing_comment,
                    ),
                )
                incident_id = cursor.lastrowid
                add_comment(conn, incident_id, None, "Created", initial, created)
                add_comment(conn, incident_id, primary_team_id, "OPEN", "Taking into account. Initial checks have started.", created + timedelta(minutes=5))
                add_comment(conn, incident_id, primary_team_id, "Update", "Reviewed the application status, relevant logs, and current dependencies.", created + timedelta(minutes=18))

                # Every other seeded incident exercises one or two realistic handoffs.
                if variation in (1, 3):
                    second_team = teams[(scenario_index + variation + 1) % len(teams)]["id"]
                    add_comment(conn, incident_id, primary_team_id, "Transferred", "Transferred for focused investigation after initial analysis.", created + timedelta(minutes=29))
                    add_comment(conn, incident_id, second_team, "OPEN", "Taking into account. Reviewing the transferred analysis and relevant component.", created + timedelta(minutes=34))
                    add_comment(conn, incident_id, second_team, "Update", "Completed specialist checks and shared findings with the owning team.", created + timedelta(minutes=45))
                    closing_team = second_team
                    if variation == 3:
                        third_team = teams[(scenario_index + variation + 2) % len(teams)]["id"]
                        add_comment(conn, incident_id, second_team, "Transferred", "Transferred after specialist analysis for final validation.", created + timedelta(minutes=49))
                        add_comment(conn, incident_id, third_team, "OPEN", "Taking into account. Validating the proposed corrective action.", created + timedelta(minutes=52))
                        closing_team = third_team
                else:
                    closing_team = primary_team_id

                add_comment(conn, incident_id, closing_team, "Closed", closing_comment, created + timedelta(minutes=63))
                added += 1
        conn.commit()
    print(f"Added {added} synthetic closed incidents.")


if __name__ == "__main__":
    main()
